### ISSUE TITLE
Could not install nools

### ISSUE THREAD

**Issue by llauren** [binarybucks/homA#129]
Pardon my nubicity, but i have no idea whether this error is due to the homA Rules component or something else.

I tried running the `rules` component and got informed that i don't have the `nools` node module installed. So i run `npm install` and get a bunch of ugly error messaging. The failure begins with

```
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm ERR! failed to fetch https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm ERR! error installing commander@1.1.1
npm ERR! error installing nools@0.2.2
```

For reasons beyond my understanding, all other `npm http GET` lines have a simple url whereas the failing keypress url has the unexpected hypen and an actual file name. It might all be my fault or lack of understanding and in no way an issue at all, but if you could just nudge me in the right direction, i'd be more than happy.

**Comment by simonvanderveldt** [comment]
ping @llauren is this still happening for you?
It worked for me with no problems whatsoever, maybe it was a temporary glitch in combination with a specific/older node/npm version?

**Comment by llauren** [comment]
Hi @simonvanderveldt ! Good to see you working on this project!

I haven't tried this for quite some time, so i cannot confirm i still have a problem. You can close this bug and i'll re-open it if i still get problems :smile:

**Comment by llauren** [comment]
Cannot replicate.

**Comment by simonvanderveldt** [comment]
:+1:
